
sudo: false

language: ruby

matrix:
  include:
    - os: linux
      rvm: 2.5.0
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      rvm: 2.4.2
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: osx
      rvm: 2.5.0
    - os: osx
      rvm: 2.4.2

before_script:
  - eval "${MATRIX_EVAL}"
  - gem build agoo.gemspec
  - gem install oj
  - gem install agoo-*
  - cd ext/agoo
  - ruby extconf.rb && make clean all
  - cd ../..

script:
  - cd test && ./tests.rb -v
